### ISSUE TITLE
Thank you, do you plan to release on CF or should i go thru with the license system they have for non curse mods

### ISSUE THREAD

**Issue by EndangeredNayla** [lostmyself8/Mekanism-Extras#1]

**Comment by lostmyself8** [comment]
I will upload the mod to CF, but I‘m currently unable to connect to CF. I have been trying to connect recently and hope I can connect.
And~~~What is the license you mentioned? It's my first time using Curse, and I don't quite understand it.

**Comment by lostmyself8** [comment]
I have already uploaded it to CF.

**Comment by lostmyself8** [comment]
I have already uploaded it to CF.
