### ISSUE TITLE
升级到1.2.1版本后卡服，急！

### ISSUE THREAD

**Issue by JackZhangCNCC** [lostmyself8/Mekanism-Extras#10]
spark查看该模组下的org.fusesource.jansi.internal.Kernel32.WriteConsoleW()17.26%24632ms (self: 24632ms - 17.26%)事件异常卡服
具体spark地址https://spark.lucko.me/rRN7slkEMj
建议作者留个联系方式，最近一直在玩这个模组，有问题第一时间找你反馈

**Comment by JackZhangCNCC** [comment]
后台报[16:47:31 ERROR]: ClassCastException error :: LogisticalTransporterBase cast to ExtraLogisticalTransporterBase -> error :: coordinates: BlockPos{x=1568, y=74, z=-2110}
经查看是一处同时连接化学结晶器和终极物流管道的至尊物流管道。我怀疑是你模组的物流管道的问题

**Comment by lostmyself8** [comment]
今天出去了；应该就是至尊管道的问题，不要把那些管道混接，估计是速度太快了会卡物品（应该是堆在管道里了所以会卡），挖掉管道后会喷射到很远的地方去。

**Comment by lostmyself8** [comment]
你去B站搜“UID:57061177”，我私信发你QQ。

**Comment by JackZhangCNCC** [comment]
好好好和蜜桃猫过节去了是吧；
话说这个准备修复吗，还是就默认让玩家别混接了
