### ISSUE TITLE
dont use upgrade tier gennerator ?

### ISSUE THREAD

**Issue by TiMNe123** [lostmyself8/Mekanism-Extras#13]
i see upgrade tier card while i dont use it... bruhh

**Comment by lostmyself8** [comment]
I haven't joined any other factories yet.
I'm still considering whether to join them or not。
You can use it on Fluid Tank,Chemical Tank,Cube and Bin.

**Comment by TiMNe123** [comment]
hmm....my naquah reactor creat stream coolant.... is it correct? @@

**Comment by lostmyself8** [comment]
After the reactor is turned on, if the fuel supply is insufficient, the reactor will shut down. At this time, the residual heat of the reactor will heat water to produce steam. You need to re-add fuel and hohlraum. If the temperature is relatively high at this time, the reactor will start up again. Removing the remaining steam will continue to produce pcs. :)
