### ISSUE TITLE
[BUG]服务器上无法启动

### ISSUE THREAD

**Issue by ZHENGLOC** [lostmyself8/Mekanism-Extras#2]
启动直接崩
[crash-2024-05-26_18.17.02-fml.txt](https://github.com/lostmyself8/Mekanism-Extras/files/15447069/crash-2024-05-26_18.17.02-fml.txt)

**Comment by lostmyself8** [comment]
I don't have the ability to set up a server here, but I think that's the reason. You can try version 1.0.2 in the "libs" folder. If there are any further errors, please report them again and I will try my best to maintain them.

**Comment by ZHENGLOC** [comment]
> I don't have the ability to set up a server here, but I think that's the reason. You can try version 1.0.2 in the "libs" folder. If there are any further errors, please report them again and I will try my best to maintain them.

👍it working now
