### ISSUE TITLE
Can not load properly

### ISSUE THREAD

**Issue by LuckyDog322** [lostmyself8/Mekanism-Extras#5]
1.20.1
version：1.1.2
[crash-2024-06-18_09.21.59-fml.txt](https://github.com/user-attachments/files/15879007/crash-2024-06-18_09.21.59-fml.txt)

**Comment by blblkang** [comment]
I'm having this problem too.
Same version.
[Uploading crash-2024-06-18_09.28.00-fml.txt…]()

**Comment by lostmyself8** [comment]
Try version 1.1.3
