### ISSUE TITLE
[1.20.1] [SMP] Cannot pick up induction matrix blocks

### ISSUE THREAD

**Issue by ptk2003** [lostmyself8/Mekanism-Extras#7]
When i mine it atomic deconstructor block just break, nothing dropping.
Diamond pickaxe same, but time to break too long.

Thanks for wonderful mod :)
1.20.1-forge-47.3.1
Mekanism-1.20.1-10.4.8.43
mekanism_extras-1.1.3

**Comment by lostmyself8** [comment]
I think I forgot to add a loot_table,sorry.
I will add it.
