### ISSUE TITLE
Add the ability to use alloy upgrade cables

### ISSUE THREAD

**Issue by ReallyChooseC** [lostmyself8/Mekanism-Extras#8]
Mekanism originally allowed the use of alloys to upgrade eight nearby cables
But not this module.
Is it possible to have alloy upgrade cables?
It would be really useful for massive low-level cable upgrades.
Chinese：
中文：
通用机械原本允许使用合金升级附近八个线缆/管道
但这个模组不行
能否让合金升级线缆？
对于大规模的低级线缆升级真的很有用

**Comment by lostmyself8** [comment]
In the initial test version, this function was available. However, due to code issues, I couldn't properly solve the problem that the mek alloy could substitute for the extra alloy. Therefore, I temporarily disabled this function.
中文:
在最开始的测试版是有这个功能的，但是由于代码的原因我没有很好的解决mek的合金也能代替本模组的合金的问题，因此我暂时将这个功能屏蔽了。

**Comment by blblkang** [comment]
> In the initial test version, this function was available. However, due to code issues, I couldn't properly solve the problem that the mek alloy could substitute for the extra alloy. Therefore, I temporarily disabled this function. 中文: 在最开始的测试版是有这个功能的，但是由于代码的原因我没有很好的解决mek的合金也能代替本模组的合金的问题，因此我暂时将这个功能屏蔽了。

Any plans to fix this feature later?
中文：
之后有计划修复这个功能吗？

**Comment by lostmyself8** [comment]
I want to fix it. But there may be some difficulties, and both my friends and I are trying to find a way.
中文：
我是想修复的。但是可能会有些困难，我和我的朋友都在想办法。

**Comment by lostmyself8** [comment]
But the short-term goals are siliceous rock ore and some multi block machines,I will focus on fix this bug after these things are completed.
中文：
不过近期的目标是硅岩矿石和一些多方块机器，等所有东西都制作完成了，才会着重处理这个问题。

**Comment by lostmyself8** [comment]
我把这个bug修复了还包括工厂升级那些，但估计没这么快发新版本。
